datamall:
  outputs:
    dev:
      dev:
      account: "{{ env_var('SF_ACCOUNT') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      role: "{{ env_var('SF_ROLE') }}"
      threads: 8
      type: snowflake
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}" 
      schema: "{{ env_var('SF_SCHEMA') }}"  
  target: dev
